name: LiteFileServer
version: 0.0.1
description: skymom application
dependencies:
  mongo_dart: any
  jsonx: ">=2.0.0 <3.0.0"
  browser: any
  google_oauth2_client: ">=0.4.1 <0.5.0"
  queries: ">=0.0.15 <0.1.0"
  stream: ">=1.3.1 <2.0.0"
dev_dependencies:
#  unittest: any
